language: rust

rust:
    - nightly

sudo: false

notifications:
    email:
        on_success: never
        on_failure: always

script:
    - cargo build
    - cargo rustc --target x86_64-unknown-nepheliad -- -Z no-landing-pads
    - cargo test
    - cargo doc --no-deps
    - rustdoc --test README.md -L target/debug

after_success:
    - curl https://mvdnes.github.io/rust-docs/travis-doc-upload.sh | bash
